import {
    CnAlarmNotification,
    CnNodeNotification,
    CnRmiAsyncConfirm,
    CnRmiAsyncRequest,
    CnRmiAsyncResponse,
    CnRmiRequest,
    CnRmiResponse,
    CnRpdoNotification,
    CnRpdoRequest,
    CnTimeConfirm,
    CnTimeRequest,
    NullMessage,
    Opcode,
    RegisterDeviceRequest,
    StartSessionConfirm,
    StartSessionRequest,
} from './protocol/comfoConnect.js';

export const opcodes = {
    [Opcode.NO_OPERATION]: NullMessage,
    [Opcode.SET_ADDRESS_REQUEST]: NullMessage,
    [Opcode.REGISTER_DEVICE_REQUEST]: RegisterDeviceRequest,
    [Opcode.START_SESSION_REQUEST]: StartSessionRequest,
    [Opcode.CLOSE_SESSION_REQUEST]: NullMessage,
    [Opcode.LIST_REGISTERED_APPS_REQUEST]: NullMessage,
    [Opcode.UNREGISTER_DEVICE_REQUEST]: NullMessage,
    [Opcode.CHANGE_PIN_REQUEST]: NullMessage,
    [Opcode.GET_REMOTE_ACCESS_ID_REQUEST]: NullMessage,
    [Opcode.SET_REMOTE_ACCESS_ID_REQUEST]: NullMessage,
    [Opcode.GET_SUPPORT_ID_REQUEST]: NullMessage,
    [Opcode.SET_SUPPORT_ID_REQUEST]: NullMessage,
    [Opcode.GET_WEB_ID_REQUEST]: NullMessage,
    [Opcode.SET_WEB_ID_REQUEST]: NullMessage,
    [Opcode.SET_PUSH_ID_REQUEST]: NullMessage,
    [Opcode.DEBUG_REQUEST]: NullMessage,
    [Opcode.UPGRADE_REQUEST]: NullMessage,
    [Opcode.SET_DEVICE_SETTINGS_REQUEST]: NullMessage,
    [Opcode.VERSION_REQUEST]: NullMessage,
    [Opcode.SET_ADDRESS_CONFIRM]: NullMessage,
    [Opcode.REGISTER_DEVICE_CONFIRM]: NullMessage,
    [Opcode.START_SESSION_CONFIRM]: StartSessionConfirm,
    [Opcode.CLOSE_SESSION_CONFIRM]: NullMessage,
    [Opcode.LIST_REGISTERED_APPS_CONFIRM]: NullMessage,
    [Opcode.UNREGISTER_DEVICE_CONFIRM]: NullMessage,
    [Opcode.CHANGE_PIN_CONFIRM]: NullMessage,
    [Opcode.GET_REMOTE_ACCESS_ID_CONFIRM]: NullMessage,
    [Opcode.SET_REMOTE_ACCESS_ID_CONFIRM]: NullMessage,
    [Opcode.GET_SUPPORT_ID_CONFIRM]: NullMessage,
    [Opcode.SET_SUPPORT_ID_CONFIRM]: NullMessage,
    [Opcode.GET_WEB_ID_CONFIRM]: NullMessage,
    [Opcode.SET_WEB_ID_CONFIRM]: NullMessage,
    [Opcode.SET_PUSH_ID_CONFIRM]: NullMessage,
    [Opcode.DEBUG_CONFIRM]: NullMessage,
    [Opcode.UPGRADE_CONFIRM]: NullMessage,
    [Opcode.SET_DEVICE_SETTINGS_CONFIRM]: NullMessage,
    [Opcode.VERSION_CONFIRM]: NullMessage,
    [Opcode.GATEWAY_NOTIFICATION]: NullMessage,
    [Opcode.KEEP_ALIVE]: NullMessage,
    [Opcode.FACTORY_RESET]: NullMessage,
    [Opcode.CN_TIME_REQUEST]: CnTimeRequest,
    [Opcode.CN_TIME_CONFIRM]: CnTimeConfirm,
    [Opcode.CN_NODE_REQUEST]: NullMessage,
    [Opcode.CN_NODE_NOTIFICATION]: CnNodeNotification,
    [Opcode.CN_RMI_REQUEST]: CnRmiRequest,
    [Opcode.CN_RMI_RESPONSE]: CnRmiResponse,
    [Opcode.CN_RMI_ASYNC_REQUEST]: CnRmiAsyncRequest,
    [Opcode.CN_RMI_ASYNC_CONFIRM]: CnRmiAsyncConfirm,
    [Opcode.CN_RMI_ASYNC_RESPONSE]: CnRmiAsyncResponse,
    [Opcode.CN_RPDO_REQUEST]: CnRpdoRequest,
    [Opcode.CN_RPDO_CONFIRM]: NullMessage,
    [Opcode.CN_RPDO_NOTIFICATION]: CnRpdoNotification,
    [Opcode.CN_ALARM_NOTIFICATION]: CnAlarmNotification,
    [Opcode.CN_FUP_READ_REGISTER_REQUEST]: NullMessage,
    [Opcode.CN_FUP_READ_REGISTER_CONFIRM]: NullMessage,
    [Opcode.CN_FUP_PROGRAM_BEGIN_REQUEST]: NullMessage,
    [Opcode.CN_FUP_PROGRAM_BEGIN_CONFIRM]: NullMessage,
    [Opcode.CN_FUP_PROGRAM_REQUEST]: NullMessage,
    [Opcode.CN_FUP_PROGRAM_CONFIRM]: NullMessage,
    [Opcode.CN_FUP_PROGRAM_END_REQUEST]: NullMessage,
    [Opcode.CN_FUP_PROGRAM_END_CONFIRM]: NullMessage,
    [Opcode.CN_FUP_READ_REQUEST]: NullMessage,
    [Opcode.CN_FUP_READ_CONFIRM]: NullMessage,
    [Opcode.CN_FUP_RESET_REQUEST]: NullMessage,
    [Opcode.CN_FUP_RESET_CONFIRM]: NullMessage,
} as const;

export const requestMessages = {
    [Opcode.REGISTER_DEVICE_REQUEST]: Opcode.REGISTER_DEVICE_CONFIRM,
    [Opcode.START_SESSION_REQUEST]: Opcode.START_SESSION_CONFIRM,
    [Opcode.CN_RMI_ASYNC_REQUEST]: Opcode.CN_RMI_ASYNC_CONFIRM,
    [Opcode.CN_RPDO_REQUEST]: Opcode.CN_RPDO_CONFIRM,
    [Opcode.CN_TIME_REQUEST]: Opcode.CN_TIME_CONFIRM,
    [Opcode.KEEP_ALIVE]: Opcode.NO_OPERATION,
} as const;
