name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - run: pnpm lint
      - run: pnpm prettier:check
      - run: pnpm build
      - name: Run Tests
        run: pnpm test:coverage
      - name: Report Test Coverage
        if: always() 
        uses: davelosert/vitest-coverage-report-action@v2
      - name: Publish Test Report
        uses: ctrf-io/github-test-reporter@v1
        with:
          report-path: './vitest-ctrf/*.json'
        if: always()
