name: Release

on:
  workflow_dispatch:
    inputs:
      versionBump:
        description: 'Select a version bump: patch, minor, or major'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
        default: patch

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm test
      - run: pnpm pack
      - name: Bump version
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"
          pnpm version ${{ github.event.inputs.versionBump }}
          echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV
          git push --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish
        run: | 
          pnpm publish --no-git-checks --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ env.VERSION }}"
          name: Release ${{ env.VERSION }}
          files: "*.tgz"
          generate_release_notes: true
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
